### PR TITLE
Add deploy scripts and files

### PR DESCRIPTION
**Pull request by georgewoodhead**

### CODE REVIEW

**Comment by rlh1994** [comment]
Looks really good, flows really well and Activating to me feels like a much better word than Deploying! Pretty much every comment here is a nitpick/idea so feel free to ignore most of them. Also a lot of my ideas are links to external, I'm not sure if that's something we want to do?

- 💡: Could you link out to the various product pages for the technologies at the start of the first page? 
- ⛏: Move the "Once finished..." line on the introductiuon page above the image so they know what they are going to get from this without scrolling down
-  💡: Bottom of Feature Exploration, could you make the dbt line an idea admonition?
-  💡: Model training, can we link to the databrick docs for how to import the notebook?
-  💡:  In model training, the hyperparamater tuning description is great but also just a complicated subject - is there a link somewhere that explains the concepts of F1/2 in detail for those interested?
-  💡:  After the importance score plot on Model Training, is it worth adding a little text block that just calls out the obvious i.e. "We see that scrolled percentage and time on the page are the most important features, which we would expect blah blah blah"?
- 🚫: Your notebook on the Using Your Model page doesn't have any of the graphs displayed 
- 💡: In the creating an audience page we see them use the model but we don't really explain the benefits of what we are doing (maybe most users will know, but as we're crossing marketting+data science maybe not), is it worth fleshing out the step 2 a bit and explaining the "power" of what we did i.e. we are now only marketting to users with a high propensity to convert, leading to higher conversion rates for the same advertising spend?

Love the dashboard images at the end, shows what people will be able to make once they have this live which is awesome!

**Review by emielver — CHANGES_REQUESTED** [review]
Hey George, it looks really good, amazing work on this!

**Introduction**
- "This accelerator demonstrates the concept of a Composable CDP...". Would we want to specify here already that this accelerator actually helps the user build this composable CDP, rather than just showing a concept of one? The concept makes it feel more like it should just be a blog post about what you can do, rather than an accelerator showing **how** you can do it.High
- "**Hightouch** activation platform... into **the** qualified leads." Should you remove "the" from the sentence?
- "**Data activation** - With Hightouch... you can enable **our** marketing teams" Should be "your"
- General comment: Might also be worth mentioning around the diagram that we're not going into detail on using a data loader like Fivetran in this accelerator

**Predictive ML Modelling: Model Training**
- In the first cell block in the embedded notebook, would it be better to link Snowplow's website inside [website](https://www.snowplow.io), rather than saying "...from Snowplow's [snowplow.io](https://snowplow.io/) website...."?
 
**Predictive ML Modelling: Using your Model**
 - Same as above with the snowplow.io link
 - Can we make the space for the embedded notebook larger? It would be great to see more of it like in the previous section on "Model Training", but no worries if not
 - Is it the idea that `display(df_spark)` shows some output? If not, it would be cool to show table output here in the embedded notebook to give people an idea of what data they should have and to get them excited to start activating their data in the next section

**Next Steps: Productionizing ML Model**
- Should we call this section "Productionizing your ML Model"?
- I think American spelling dictates using "learned" instead of "learnt".

**Next Steps: Visualize Ad Campaign Performance**
- Again maybe we should have the title of "Visualize your Ad Campaign Performance"?

Maybe lastly it could be good to add a summary text or section, just to remind people what they should have built, what value they should be getting out of that and then leaving it open for next steps (maybe pointing to the Accelerators hub where they can find more ideas of what to do with their Snowplow data). What do you think?

Either way this is really really cool, it looks great!

**Review by rlh1994 — CHANGES_REQUESTED** [review]
Looks really good, flows really well and Activating to me feels like a much better word than Deploying! Pretty much every comment here is a nitpick/idea so feel free to ignore most of them. Also a lot of my ideas are links to external, I'm not sure if that's something we want to do?

-  💡: Could you link out to the various product pages for the technologies at the start of the first page?
-  ⛏: Move the "Once finished..." line on the introductiuon page above the image so they know what they are going to get from this without scrolling down
-  💡: Bottom of Feature Exploration, could you make the dbt line an idea admonition?
-  💡: Model training, can we link to the databrick docs for how to import the notebook?
-  💡: In model training, the hyperparamater tuning description is great but also just a complicated subject - is there a link somewhere that explains the concepts of F1/2 in detail for those interested?
-  💡: After the importance score plot on Model Training, is it worth adding a little text block that just calls out the obvious i.e. "We see that scrolled percentage and time on the page are the most important features, which we would expect blah blah blah"?
-  🚫: Your notebook on the Using Your Model page doesn't have any of the graphs displayed
- 💡: In the creating an audience page we see them use the model but we don't really explain the benefits of what we are doing (maybe most users will know, but as we're crossing marketting+data science maybe not), is it worth fleshing out the step 2 a bit and explaining the "power" of what we did i.e. we are now only marketting to users with a high propensity to convert, leading to higher conversion rates for the same advertising spend?
- 💡: Agree with Emiel about a nice summary of "Look what you did, you're great"

Love the dashboard images at the end, shows what people will be able to make once they have this live which is awesome!

**Review by emielver — CHANGES_REQUESTED** [review]
LGTM as well! Only thing is that `Visualize your Ad Campaign Performance` might be too long since the rendering seems to be off in the sidebar for me. We can remove the "your" again to ensure that it looks good, or otherwise make the sidebar a bit wider? I think removing "your" would be preferable though, WDYT?

**Comment by georgewoodhead** [comment]
Thanks @rlh1994 and @emielver  for your feedback, all great points! 

@emielver I'll remove "your" for now to make it fit. Also really like your idea of pointing to the Accelerators hub as the final step in the summary and we could show recommended accelerators to do next. I'll add this as an enhancement issue for when we have a hub to link to!

**Review by emielver — APPROVED** [review]
LGTM! Great job on this!

**Pull request merged**
